### ISSUE TITLE
App icon missing/blank in MacOS ARM64 build

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwutils/nw-builder#1279]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

https://stackoverflow.com/questions/79106055/nw-js-nw-builder-not-displaying-icon-on-macos-arm64-demo-project
Refer to this Stack Overflow thread.

### Expected/Proposed Behaviour

App icon should not be missing/blank.

### Additional Info

- Package version:
- Operating System:
- Node version:
- NW.js version:
- Repro link: https://github.com/me-vlad-k/nwbuilder-demo
- ...

**Comment by ayushmanchhabra** [comment]
@me-vlad-k Will look into this soon

**Comment by me-vlad-k** [comment]
@ayushmanchhabra  I found a solution to this 'issue'.

The problem was with the **.icns** file itself. I had found a dummy icon somewhere on the web, and since it was created incorrectly, it caused this weird behavior.

**For someone who may struggle with the same issue:**

Make sure to create your .icns file correctly before you start gasping in panic—it's very important! 😄 When using an app to create a .icns file, you should start with a 1024x1024 PNG file to ensure everything looks sharp on Retina displays. If you somehow miss some icon dimensions, such as 64x64 or others, macOS will display blank icons instead of the missing ones.

There are many apps available on the web that can create .icns files for you. A few examples are iLove Icns Creator, Image2Icon, and many others, including command-line utilities.

I also removed the `"icon": "./src/icon.png"` from the NW.js manifest, as it doesn't seem to play any role in displaying an icon for macOS.

I updated my repo [nwbuilder-demo](https://github.com/me-vlad-k/nwbuilder-demo) and uploaded the new .icns file. I tested how the app is being built, and everything works for ARM64. I'll continue to tweak other settings and see what I can achieve.

**Comment by ayushmanchhabra** [comment]
To prevent this from happening in the future, we should maybe check the file headers to see if its the correct image type and throw error on invalid type.
