### ISSUE TITLE
Welcome back! :partying_face: 

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwutils/nw-builder#557]
@ayushmxn Looks like you've taken over maintenance of this repo. The NW.js community is excited to see it be brought up-to-date and grow. NW.js is awesome, but the one area I really want it to improve in is automated builds, so I'm very grateful to have you working on this project.

I've created a community website at:

* https://nwutils.io

It links to the Gitter and Discord chats if you want to hang out with the rest of us.

I've also invited you to the https://github.com/nwutils GitHub Organization as a member. We've had a few people move their projects there to get more visibility.

**Comment by ayushmxn** [comment]
Thanks! Excited to see how it grows too. The project is currently in maintainance mode and I'm assessing the state/health of the repo (see #556). I'm trying to see if it's more work to do a hard refactor to ESM or make changes incrementally.

I'll get back to you on moving the project since I currently only have write access to the repo.
