### ISSUE TITLE
Generate Installer Package of NW.js app

### ISSUE THREAD

**Issue by tharatau** [nwutils/nw-builder#611]
### Issue Type

- [ ] Bug Fix
- [x] Feature
- [ ] Other

### Current/Missing Behaviour

Unable to automate packaging of apps for different platforms.

### Expected/Proposed Behaviour

Package apps for different platforms.

### Additional Info

https://github.com/nwjs/nw.js/issues/7693#issuecomment-834856443

- Operating System:
- Node version:
- NW.js version:
- Repro link:
- ...

**Comment by sysrage** [comment]
To clarify, this Issue seems to be about automatic generation of an "installer" from the package generated by `nw-builder`. While certainly possible, it can add considerable complication since there are so many options people will want to modify for their installers. It may be better to simply suggest some options for users, once they have their generated zip/tgz file.

**Comment by tharatau** [comment]
Mostly agree now.

>  It may be better to simply suggest some options for users, once they have their generated zip/tgz file. For example, point them to the InnoSetup documentation or RPM/DEB generation documentation.

Instead of pointing to docs, I think [this project](https://github.com/nwutils/nw-global-installer) is better suited for this functionality.

**Comment by sysrage** [comment]
You can definitely list nw-global-installer as a recommendation, but I strongly disagree that it should be the *only* suggestion. That project only works for a small subset of NW.js applications. I wouldn't use it for any of my projects.

**Comment by TheJaredWilcurt** [comment]
I've been wanting a system like [nw-global-installer](https://github.com/nwutils/nw-global-installer) since like 2014. And I'd greatly appreciate anyone contributing to build out a solution that fits that dream. But until a production ready implementation is created, I would say having *any* solution in nw-builder to automate creating of an installer would be an improvement.

I'm very grateful for all the attention and work going into nw-builder. But it still isn't a comprehensive enough tool to replace [Phoenix](https://github.com/evshiron/nwjs-builder-phoenix). If Electron has shown us anything, it's that people don't want to learn anything about desktop app development, or explore the best options for each part of the process. They just want a magic button that turns a webapp into a desktop app in as few steps as possible. What installer system is used (Inno, NSIS, RAR SFX, etc) and what slight advantages/disadvantages one has over another is less important to them, whatever is *easiest* wins, until they have a good reason to deviate. Which honestly probably 95% of apps won't have a good reason to deviate.

When I create `nw-vue3-boilerplate` or `nw-angular-cli-example` my goal is to attract as many users who haven't heard of NW.js to start using it. I want to lower all the barriers of entry so they don't need any additional knowledge to start using it. I want it to be a pain free experience so they will like it, use it for their real world apps and then more examples of projects can be pointed to using NW.js. The community and the ecosystem can continue to grow.

So for those projects I have a rule that they must be this easy:

1. Getting up and running only requires downloading a copy of the repo and running `npm install && npm start`
1. The dev environment that then launches is as close to their existing dev environment as possible, it shouldn't be missing dev tools they are used to (like how Vue DevTools are built in)
1. If you are ready to ship your application to users, it only requires `npm run build` and then all platform will be packaged and ready to deploy. Admittedly, this is the part our community struggles with the most. With Phoenix I at least have a good Windows installer, but producing installers for different non-Windows OS's is just as important, but lacking currently.

I do think that if `nw-global-installer` existed, it would be the most optimal solution for the community, however until that becomes a prioritized community project, I wouldn't want to dissuade nw-builder from adding installer options to the build process, it's really the only thing holding me back from using it on my boilerplates.

**Comment by tharatau** [comment]
Leaving this open for further discussion. I'll address both your comments in time. Overall, I don't have a strong opinion on if installer capability should be included or not. I'll work on getting `nw-builder` in a more [feature complete state](https://github.com/nwutils/nw-builder/issues?q=is%3Aissue+is%3Aopen+label%3Afeature).

**Comment by tharatau** [comment]
This is good to be closed. Installer specific discussions cam happen in those issues/PRs.
